Updated to Spring Boot 2.1.4.RELEASE
hzpz/mongeez-spring-boot-starter pull request #10
Opened 2019-04-24 02:22 UTC by santam85

I updated the starter to be compatible with Spring Boot 2.1.4.RELEASE

2019-04-25 15:39 UTC, santam85 commented
@hzpz can you review this at your earliest convenience?

2019-05-17 09:53 UTC, hzpz commented
Thank you! I'll have a look.

2019-05-21 09:20 UTC, hzpz requested changes

2019-05-21 09:20 UTC, hzpz commented on pom.xml
> +    <version>2.1.5-SNAPSHOT</version>
I don't see why the version of the starter should change. I _might_ make it 2.0.0, but the PR should leave it as is.

2019-05-21 09:20 UTC, hzpz commented on src/main/java/io/github/hzpz/spring/boot/autoconfigure/mongeez/MongoDbFactoryDependsOnPostProcessor.java
> +    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) {
All changes in this class seem to be purely cosmetical. I don't see a reason for that, please revert those changes.

2019-05-21 09:20 UTC, hzpz commented on src/test/java/io/github/hzpz/spring/boot/autoconfigure/mongeez/MongeezAutoConfigurationTests.java
> +        assertNotNull(mongeezDatabase);
Why did you add this assert? If that fails then something is fundamentally wrong with this test. Therefore it should not "fail" (in JUnit terms) but error out. Which would happen anyway in the next line (caused by a `NullPointerException`).

2019-05-21 09:20 UTC, hzpz commented on src/test/java/io/github/hzpz/spring/boot/autoconfigure/mongeez/MongeezAutoConfigurationTests.java
> +            MongoAutoConfiguration.class, MongeezAutoConfiguration.class);
You seem to be using a different formatter than me. Please make sure, that you don't submit any formatting changes like this.

2019-05-21 09:20 UTC, hzpz commented on src/test/java/io/github/hzpz/spring/boot/autoconfigure/mongeez/MongeezAutoConfigurationTests.java
> +        assertNotNull(mongeezActualDatabase);
See above.

2019-05-21 09:20 UTC, hzpz commented on src/test/java/io/github/hzpz/spring/boot/autoconfigure/mongeez/MongeezAutoConfigurationTests.java
> +        assertNotNull(auth);
See above.

2019-05-21 09:20 UTC, hzpz commented on src/test/java/io/github/hzpz/spring/boot/autoconfigure/mongeez/MongeezAutoConfigurationTests.java
> +        assertNotNull(auth);
See above.

2019-05-21 12:47 UTC, santam85 commented
@hzpz changes addressed.

2019-05-21 13:10 UTC, hzpz approved these changes

2019-05-21 13:14 UTC, merged

2019-05-21 13:15 UTC, hzpz commented
Thanks again. I'll create and publish a new release in the next few days.

2019-06-25 14:43 UTC, santam85 commented
Hello @hzpz, I noticed the release for this is still pending, anything I can do to to help expedite?

2019-06-26 12:48 UTC, hzpz commented
Hey @santam85, sorry for the delay, see #12

2019-06-26 13:16 UTC, santam85 commented
Thanks!